<a href="https://colab.research.google.com/github/Phuti-ane/Python-project/blob/main/setting%20Multi%20index.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [13]:
# @title
from bs4 import BeautifulSoup
import requests
import pandas as pd

#getting the url to be used to extract information
url = 'https://en.wikipedia.org/wiki/List_of_largest_companies_in_South_Africa'

#assign the link
page = requests.get(url)
soup = BeautifulSoup(page.text, 'html')

#we only want the table first before extracting exact data
table = soup.find_all('table')[0]
#table_text = table.text.strip()


#sorting in Heading(extracting headings)
table_title = table.find_all('th')
table_title_text = [title.text.strip() for title in table_title]

#put headings in a column with panda through data frame
df = pd.DataFrame(columns = table_title_text)
#create a 2 dimension table with panda
table_colu = table.find_all('tr')

for row in table_colu[1:]:
    row_data = row.find_all('td')
    individual = [row_text.text.strip() for row_text in row_data]
    length = len(df)
    df.loc[length] = individual
df
#we call df and not print
#===============================================================================================

#sorting out data
#select the first 10 rows and sort in profit and industry

df[df['Rank'].astype(int) < 10].sort_values( by= ['Profits(US$ millions)','Industry'])

#===============================================================================================

#setting multy indexes and sorting

df.set_index(['Rank','Company'], inplace = True)
df

                                Revenue(US$ millions) Profits(US$ millions)  \
Rank Company
1    Eskom                                     13,941                −1,292
2    Sasol                                     12,989                −6,272
3    MTN Group                                 12,238                 1,341
4    Shoprite Holdings                         10,802                   230
5    Steinhoff International                    9,704                −2,910
6    Anglo American Platinum                    9,402                 2,074
7    Sibanye Gold                               8,692                 2,089
8    Spar Group                                 8,479                   134
9    Bidcorp                                    8,227                    78
10   Vodacom Group                              6,707                 1,165
11   Pick n Pay Stores                          6,351                    66
12   Naspers                                    5,934                 3,404
13   Massmart                                   5,920                  −120
14   Kumba Iron Ore                             5,466                 2,036
15   Vodacom South Africa                       5,236                   ...
16   Bidvest Group                              5,233                   −13
17   Motus                                      5,009                    13
18   Woolworths South Africa                    4,927                    38
19   Impala Platinum                            4,766                 1,125
20   Sappi                                      4,609                  −135
21   Transnet                                   4,590                  −572
22   Engen Petroleum                            4,555                  −257
23   AngloGold Ashanti                          4,427                   971
24   Pepkor                                     4,300                   ...
     Datatec                                    4,110                     6
26   Mediclinic International                   4,066                   284
27   Gold Fields                                3,982                   745
28   Remgro                                     3,734                   449
29   MultiChoice                                3,693                   278
30   Barloworld Limited                         3,390                  −171
31   Massmart Wholesale                         3,246                   ...
32   Imperial Logistics                         3,165                   −15
34   Telkom                                     2,949                   179
35   Wilson Bayly Holmes-Ovcon                  2,939                   −35
36   Transnet Freight Rail                      2,692                   ...
37   Massmart Retail                            2,654                   ...
38   Aspen Pharmacare                           2,637                   315
39   Clicks Group                               2,463                   128
40   Foschini Group                             2,428                  −127
41   Super Group                                2,359                   −11
42   RCL Foods                                  2,162                    68
43   Tiger Brands                               2,033                    71
44   Harmony Gold                               1,995                   −58
45   Exxaro                                     1,974                   716
46   Marikana                                   1,833                   947
47   Dis-Chem                                   1,793                    47
48   Life Healthcare Group                      1,732                     3
49   ArcelorMittal South Africa                 1,681                  −333
50   AECI                                       1,645                    11

                                               Industry
Rank Company
1    Eskom                             Electric utility
2    Sasol                                    Chemistry
3    MTN Group                       Telecommunications
4    Shoprite Holdings                           Retail
5    Steinhoff International                    Holding
6    Anglo American Platinum                     Mining
7    Sibanye Gold                                Mining
8    Spar Group                                  Retail
9    Bidcorp                               Agroindustry
10   Vodacom Group                   Telecommunications
11   Pick n Pay Stores                           Retail
12   Naspers                                    Holding
13   Massmart                                    Retail
14   Kumba Iron Ore                              Mining
15   Vodacom South Africa            Telecommunications
16   Bidvest Group                              Holding
17   Motus                                   Automotive
18   Woolworths South Africa                     Retail
19   Impala Platinum                             Mining
20   Sappi                               Pulp and paper
21   Transnet                                 Transport
22   Engen Petroleum                        Oil and gas
23   AngloGold Ashanti                           Mining
24   Pepkor                                     Holding
     Datatec                     Information technology
26   Mediclinic International                Healthcare
27   Gold Fields                                 Mining
28   Remgro                                     Holding
29   MultiChoice                     Telecommunications
30   Barloworld Limited                    Conglomerate
31   Massmart Wholesale                       Wholesale
32   Imperial Logistics                    Conglomerate
34   Telkom                          Telecommunications
35   Wilson Bayly Holmes-Ovcon             Construction
36   Transnet Freight Rail                    Transport
37   Massmart Retail                             Retail
38   Aspen Pharmacare                   Pharmaceuticals
39   Clicks Group                                Retail
40   Foschini Group                              Retail
41   Super Group                              Transport
42   RCL Foods                             Agroindustry
43   Tiger Brands                          Agroindustry
44   Harmony Gold                                Mining
45   Exxaro                                      Mining
46   Marikana                                    Mining
47   Dis-Chem                                Healthcare
48   Life Healthcare Group                   Healthcare
49   ArcelorMittal South Africa                   Steel
50   AECI                                     Chemicals