<a href="https://colab.research.google.com/github/Phuti-ane/Python-project/blob/main/sorting_table_with_columns.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
# @title
from bs4 import BeautifulSoup
import requests
import pandas as pd

#getting the url to be used to extract information
url = 'https://en.wikipedia.org/wiki/List_of_largest_companies_in_South_Africa'

#assign the link
page = requests.get(url)
soup = BeautifulSoup(page.text, 'html')

#we only want the table first before extracting exact data
table = soup.find_all('table')[0]
#table_text = table.text.strip()


#sorting in Heading(extracting headings)
table_title = table.find_all('th')
table_title_text = [title.text.strip() for title in table_title]

#put headings in a column with panda through data frame
df = pd.DataFrame(columns = table_title_text)
#create a 2 dimension table with panda
table_colu = table.find_all('tr')

for row in table_colu[1:]:
    row_data = row.find_all('td')
    individual = [row_text.text.strip() for row_text in row_data]
    length = len(df)
    df.loc[length] = individual
df
#we call df and not print
#===============================================================================================

#sorting out data
#select the first 10 rows and sort in profit and industry

df[df['Rank'].astype(int) < 10].sort_values( by= ['Profits(US$ millions)','Industry'])

,Rank,Company,Revenue(US$ millions),Profits(US$ millions),Industry
2,3,MTN Group,"12,238","1,341",Telecommunications
7,8,Spar Group,"8,479",134,Retail
5,6,Anglo American Platinum,"9,402","2,074",Mining
6,7,Sibanye Gold,"8,692","2,089",Mining
3,4,Shoprite Holdings,"10,802",230,Retail
8,9,Bidcorp,"8,227",78,Agroindustry
0,1,Eskom,"13,941","−1,292",Electric utility
4,5,Steinhoff International,"9,704","−2,910",Holding
1,2,Sasol,"12,989","−6,272",Chemistry